server:
  port: 8095

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: resumer
    connect-timeout: 10s
    lettuce:
      pool:
        # 链接池中最小的空闲链接 默认为0
        min-idle: 0
        # 链接池中最大的空闲连接 默认为 8
        max-idle: 8
        #连接池中最大数据库链接数 默认为8
        max-active: 8
        #连接池最大阻塞等待时间 负值表示没有限制
        max-wait: -1ms